### ISSUE TITLE
[CORE] LocalParitionWriter causes OOM during mergeSpills

### ISSUE THREAD

**Issue by ccat3z** [apache/incubator-gluten#7860] opened 2024-11-08 03:05 UTC
### Backend

VL (Velox)

### Bug description

`LocalParitionWrriter::mergeSpills` use `arrow::io::MemoryMappedFile` to read all spill files. But it is not `munmap` in time, which results in a significant consumption of `RssFile`.

### Spark version

None

**Comment by zhztheplayer** [comment] 2024-11-08 04:49
Would you like to post the OOM error message you have seen? Or it's only an abnormal consumption of rss files?

**Comment by ccat3z** [comment] 2024-11-08 05:11
![image](https://github.com/user-attachments/assets/ed5475a2-556d-4f9c-8a2c-3444b409c1de)
The error message is same as https://github.com/apache/incubator-gluten/issues/6947, killed by yarn. But the reasons are different.

**Comment by zhouyuan** [comment] 2024-11-08 07:51
CC @marin-ma

**Comment by FelixYBW** [comment] 2024-11-08 21:31
So the root cause is that the memory is unmapped until the file is close. When we merge the spills it eventually mapped all the spill data to memory. "Killed by yarn" error makes sense here. 

Let's see if the ReadableFile performance is the same as MemoryMappedFile. It's an easy fix if so. Otherwise we need to manually unmap the file.

**Comment by FelixYBW** [comment] 2024-11-08 21:34
@jinchengchenghh, what's the way Velox used to merge spill file?

Most efficient way should be mmap + MADV_SEQUENTIAL + manually munmap

**Comment by kecookier** [comment] 2024-11-09 03:05
> Would you like to post the OOM error message you have seen? Or it's only an abnormal consumption of rss files?

 @zhztheplayer  we caught this issue by dumping `/proc/self/status` when the executor is killed. It shows that `RssFile` is almost 3G when `VmRss` is 3.5G. This issue affects a number of our large-scale ETL processes. 
/proc/self/status ![image](https://github.com/user-attachments/assets/012b96c6-9bbc-4ee9-abc4-c6ae7b1334a0)

> So the root cause is that the memory is unmapped until the file is close. When we merge the spills it eventually mapped all the spill data to memory. "Killed by yarn" error makes sense here.
> 
> Let's see if the ReadableFile performance is the same as MemoryMappedFile. It's an easy fix if so. Otherwise we need to manually unmap the file.

@FelixYBW 
The Arrow `MemoryMappedFile` does not support a method to get the underlying `mmap` address. However, `MemoryMappedFile::MemoryMap` has a method to get the region data pointer, so we might add a method for `MemoryMappedFile` to return `head()` or `data()`. 

Another approach is in `mergeSpills()`, where we open the file for each partition and close it when finished. We do some internal performance test, it shows ReadableFile may have some regression.

@ccat3z Can you commit a PR and trigger the community performance benchmark by adding the comment /Benchmark Velox?

**Comment by FelixYBW** [comment] 2024-11-09 07:57
benchmark velox doesn't have spill. How much performance regression? Is the regression compared with mmap file or vanilla spark?

**Comment by FelixYBW** [comment] 2024-11-09 08:07
@marin-ma see if we can have any way to call madvise(MADV_SEQUENTIAL), it should be able to release physical memory quickly.

**Comment by ccat3z** [comment] 2024-11-09 08:56
> @marin-ma see if we can have any way to call madvise(MADV_SEQUENTIAL), it should be able to release physical memory quickly.

I tested the following patch on arrow, it seems that it will not be released immediately. It might still require explicit 'MADV_DONTNEED' in this case. 

```
diff -ru apache-arrow-15.0.0.orig/cpp/src/arrow/io/file.cc apache-arrow-15.0.0/cpp/src/arrow/io/file.cc
--- apache-arrow-15.0.0.orig/cpp/src/arrow/io/file.cc   2024-11-09 11:39:58.497266369 +0800
+++ apache-arrow-15.0.0/cpp/src/arrow/io/file.cc        2024-11-09 14:50:37.035869206 +0800
@@ -41,6 +41,7 @@
 #include <sstream>
 #include <string>
 #include <utility>
+#include <iostream>

 // ----------------------------------------------------------------------
 // Other Arrow includes
@@ -575,6 +576,12 @@
       return Status::IOError("Memory mapping file failed: ",
                              ::arrow::internal::ErrnoMessage(errno));
     }
+    int madv_res = madvise(result, mmap_length, MADV_SEQUENTIAL);
+    if (madv_res != 0) {
+      return Status::IOError("madvise failed: ",
+                             ::arrow::internal::ErrnoMessage(errno));
+    }
+    std::cerr << "madvise success: " << result << " " << mmap_length << std::endl;
     map_len_ = mmap_length;
     offset_ = offset;
     region_ = std::make_shared<Region>(shared_from_this(), static_cast<uint8_t*>(result),
@@ -720,6 +727,27 @@
   return ::arrow::internal::MemoryAdviseWillNeed(regions);
 }
```

**Comment by FelixYBW** [comment] 2024-11-09 09:56
>    return ::arrow::internal::MemoryAdviseWillNeed(regions);
>  }
> ```

Does it call another madvise later? it will override previous one.

**Comment by FelixYBW** [comment] 2024-11-09 10:17
MemoryMappedFile has Region, when region is destructed, it called munmap. See how we can take use of it.

**Comment by marin-ma** [comment] 2024-11-11 01:49
> Another approach is in mergeSpills(), where we open the file for each partition and close it when finished.
@kecookier Not sure how much performance impact this might introduce. This approach requires invoking mmap and munmap for each partition, and some partitions in a single spill file may be quite small.

> We do some internal performance test, it shows ReadableFile may have some regression.
How much performance regression do you see? Could you share some results? Thanks!

**Comment by jinchengchenghh** [comment] 2024-11-11 02:17
Velox use `SpillReadFile` to read the file, it uses `FileInputStream` to read the file and `simd::memcpy` to copy the bytes, It will output batch RowVector one by one. `FileInputStream` uses `velox::LocalReadFile` `pread` or `preadv` to read the file.

As I see, it reads bufferSize_  which is controlled by QueryConfig `kSpillReadBufferSize` (default 1MB) one time. Note: if file system supports async read, read double bufferSize_ one time.
@FelixYBW 
```
readBytes = readSize();
      VELOX_CHECK_LT(
          0, readBytes, "Read past end of FileInputStream {}", fileSize_);
      NanosecondTimer timer_2{&readTimeNs};
      file_->pread(fileOffset_, readBytes, buffer()->asMutable<char>());

uint64_t FileInputStream::readSize() const {
  return std::min(fileSize_ - fileOffset_, bufferSize_);
}
```
```
/* Read data from file descriptor FD at the given position OFFSET
   without change the file pointer, and put the result in the buffers
   described by IOVEC, which is a vector of COUNT 'struct iovec's.
   The buffers are filled in the order specified.  Operates just like
   'pread' (see <unistd.h>) except that data are put in IOVEC instead
   of a contiguous buffer.

   This function is a cancellation point and therefore not marked with
   __THROW.  */
extern ssize_t preadv (int __fd, const struct iovec *__iovec, int __count,
		       __off_t __offset) __wur;
```

**Comment by ccat3z** [comment] 2024-11-11 03:44
> How much performance regression do you see? Could you share some results? Thanks!

@marin-ma After internal re-testing last weekend, no noticeable performance regression was found.

**Comment by ccat3z** [comment] 2024-11-11 03:51
> In io_util.cc, madvise(willneed) is called again. You may disable it.

The new patch is here, but it's not working either. There might still be some codes that haven't been found, I'll recheck it if required.

``` patch
diff -ru apache-arrow-15.0.0.orig/cpp/src/arrow/io/file.cc apache-arrow-15.0.0/cpp/src/arrow/io/file.cc
--- apache-arrow-15.0.0.orig/cpp/src/arrow/io/file.cc   2024-11-09 11:39:58.497266369 +0800
+++ apache-arrow-15.0.0/cpp/src/arrow/io/file.cc        2024-11-09 18:09:06.540567675 +0800
@@ -41,6 +41,7 @@
 #include <sstream>
 #include <string>
 #include <utility>
+#include <iostream>

 // ----------------------------------------------------------------------
 // Other Arrow includes
@@ -575,6 +576,12 @@
       return Status::IOError("Memory mapping file failed: ",
                              ::arrow::internal::ErrnoMessage(errno));
     }
+    int madv_res = madvise(result, mmap_length, MADV_SEQUENTIAL);
+    if (madv_res != 0) {
+      return Status::IOError("madvise failed: ",
+                             ::arrow::internal::ErrnoMessage(errno));
+    }
+    std::cerr << "madvise success: " << result << " " << mmap_length << std::endl;
     map_len_ = mmap_length;
     offset_ = offset;
     region_ = std::make_shared<Region>(shared_from_this(), static_cast<uint8_t*>(result),
@@ -660,8 +667,8 @@
   ARROW_ASSIGN_OR_RAISE(
       nbytes, internal::ValidateReadRange(position, nbytes, memory_map_->size()));
   // Arrange to page data in
-  RETURN_NOT_OK(::arrow::internal::MemoryAdviseWillNeed(
-      {{memory_map_->data() + position, static_cast<size_t>(nbytes)}}));
+  // RETURN_NOT_OK(::arrow::internal::MemoryAdviseWillNeed(
+  //     {{memory_map_->data() + position, static_cast<size_t>(nbytes)}}));
   return memory_map_->Slice(position, nbytes);
 }
```

**Comment by FelixYBW** [comment] 2024-11-12 21:06
If ReadableFile doesn't have significant perf loss, let's use the quick fix and optimize it to mmap in future. @marin-ma can you test #7861 on our jenkins with spill?

**Comment by FelixYBW** [comment] 2024-11-12 21:09
> Velox use `SpillReadFile` to read the file, it uses `FileInputStream` to read the file and `simd::memcpy` to copy the bytes, It will output batch RowVector one by one. `FileInputStream` uses `velox::LocalReadFile` `pread` or `preadv` to read the file.

The optimal way should be we map like 1M each time, unmap it once accessed. Looks MemoryMappedFile::Region can implement it.

**Comment by FelixYBW** [comment] 2024-11-12 21:13
> > In io_util.cc, madvise(willneed) is called again. You may disable it.
> 
> The new patch is here, but it's not working either. There might still be some codes that haven't been found, I'll recheck it if required.
> 
> ```diff
> diff -ru apache-arrow-15.0.0.orig/cpp/src/arrow/io/file.cc apache-arrow-15.0.0/cpp/src/arrow/io/file.cc
> --- apache-arrow-15.0.0.orig/cpp/src/arrow/io/file.cc   2024-11-09 11:39:58.497266369 +0800
> +++ apache-arrow-15.0.0/cpp/src/arrow/io/file.cc        2024-11-09 18:09:06.540567675 +0800
> @@ -41,6 +41,7 @@
>  #include <sstream>
>  #include <string>
>  #include <utility>
> +#include <iostream>
> 
>  // ----------------------------------------------------------------------
>  // Other Arrow includes
> @@ -575,6 +576,12 @@
>        return Status::IOError("Memory mapping file failed: ",
>                               ::arrow::internal::ErrnoMessage(errno));
>      }
> +    int madv_res = madvise(result, mmap_length, MADV_SEQUENTIAL);
> +    if (madv_res != 0) {
> +      return Status::IOError("madvise failed: ",
> +                             ::arrow::internal::ErrnoMessage(errno));
> +    }
> +    std::cerr << "madvise success: " << result << " " << mmap_length << std::endl;
>      map_len_ = mmap_length;
>      offset_ = offset;
>      region_ = std::make_shared<Region>(shared_from_this(), static_cast<uint8_t*>(result),
> @@ -660,8 +667,8 @@
>    ARROW_ASSIGN_OR_RAISE(
>        nbytes, internal::ValidateReadRange(position, nbytes, memory_map_->size()));
>    // Arrange to page data in
> -  RETURN_NOT_OK(::arrow::internal::MemoryAdviseWillNeed(
> -      {{memory_map_->data() + position, static_cast<size_t>(nbytes)}}));
> +  // RETURN_NOT_OK(::arrow::internal::MemoryAdviseWillNeed(
> +  //     {{memory_map_->data() + position, static_cast<size_t>(nbytes)}}));
>    return memory_map_->Slice(position, nbytes);
>  }
> ```

Thank you for your test. Can you try posix_fadvise? We have a case to show madvise doesn't work on file mapping.

**Comment by ccat3z** [comment] 2024-11-13 02:48
> Just found some test:
> 
> ![image](https://private-user-images.githubusercontent.com/47296334/385467525-86f069b0-de8d-4f1d-9858-b5e0bdf68418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjU4MDgsIm5iZiI6MTczMTQ2NTUwOCwicGF0aCI6Ii80NzI5NjMzNC8zODU0Njc1MjUtODZmMDY5YjAtZGU4ZC00ZjFkLTk4NTgtYjVlMGJkZjY4NDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAyMzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNTQ4NjgwZDkzZGU5ZWJhY2VlMjRlNGMwN2VkMzJkZmYwZmNkYWZjODAxNjdhYzZhOWY2MGVhNDk2YTEyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9_5fViF9SrDHXbHHUouNCSwZnaFhhpfItSQFwmqglys)

Could you introduce what each columns in stdout represents?

**Comment by FelixYBW** [comment] 2024-11-13 03:06
> Could you introduce what each columns in stdout represents?

Not sure :( It's a test two years ago.

**Comment by FelixYBW** [comment] 2024-11-13 21:23
some link about mmap we referred before.

http://xoyo.space/2017/11/mmap-performance-analyzing-and-tuning/
https://github.com/xoyowade/mmap_benchmark
https://stackoverflow.com/questions/30470972/using-mmap-and-madvise-for-huge-pages
https://lwn.net/Articles/590693/

**Comment by FelixYBW** [comment] 2024-11-13 21:25
summary:
![image](https://github.com/user-attachments/assets/620b5610-b76d-4a57-b43c-f58b35e450eb)

**Comment by ccat3z** [comment] 2024-11-14 10:33
I wrote a simple [gist](https://gist.github.com/ccat3z/c0d81b0ddeb7276eeff16844528a6876) to dump memory usage during reading file. Both `MADV_DONTNEED` and `munmap` can release RssFile immediately. And `MAP_POPULATE` significantly improve performance. However, `MAP_POPULATE` will use hundreds of MB of untrackable RssFile, which is not acceptable in this case.

So I believe that the combination of manual `MDAV_WILLNEED` and `MADV_DONTNEED` is the best solution. I will test it in gluten later.

**Closed** 2024-11-28 10:58 UTC
Labels: bug, triage
