### ISSUE TITLE
UT failures for Spark3.5

### ISSUE THREAD

**Issue by yma11** [apache/incubator-gluten#5341] opened 2024-04-09 11:30 UTC
### Backend

VL (Velox)

### Bug description
Note that following list doesn't include the possible failures for the UTs newly added Spark3.5. Will update the list once them collected.
- [x] generate hash join plan - v2
- [ ] test write parquet with compression codec
- [ ] regr_r2
- [ ] regr_slope
- [ ] regr_intercept
- [ ] regr_sxy
- [x] input row
- [x] test hive static partition write table
- [x] test hive write table
- [x] test hive write dir

- [x] column mapping mode = id
- [x] column mapping mode = name
- [x] delta: time travel
- [x] delta: partition filters
- [x] basic test with stats.skipping disabled
- [x] column mapping with complex type

- [x] iceberg bucketed join
- [x] iceberg bucketed join with partition
- [x] iceberg bucketed join with partition filter

- [x] GlutenExpressionMappingSuite
- [x] SPARK-26708 Cache data and cached plan should stay consistent
- [x] SPARK-46590 adaptive query execution works correctly with broadcast join and union
- [x] SPARK-46590 adaptive query execution works correctly with cartesian join and union
- [x] SPARK-40618: Regression test for merging subquery bug with nested subqueries
- [x] SPARK-40615: Check unsupported data type when decorrelating subqueries
- [x] SPARK-40618: Regression test for merging subquery bug with nested subqueries

- [x] Gluten - test for FAILFAST parsing mode
- [x] SPARK-36612: Support left outer join build left or right outer join build right in shuffled hash join
- [x] A cached table preserves the partitioning and ordering of its cached SparkPlan
- [ ] SPARK-42782: Hive compatibility check for get_json_object
- [x] SPARK-43876: Enable fast hashmap for distinct queries
- [x] SPARK-41896: Filter on row_index and a stored column at the same time
- [x] SPARK-43450: Filter on full _metadata column struct
- [x] SPARK-43450: Filter on aliased _metadata.row_index

- [x] SPARK-45171: Handle evaluated nondeterministic expression (VeloxRuntimeError: the key in unnest Operator only support field)

### Spark version

None

**Comment by FelixYBW** [comment] 2024-04-09 18:13
does it cover all the UT failures of 3.5? If so let's pin to top

**Comment by yma11** [comment] 2024-04-10 00:12
> does it cover all the UT failures of 3.5? If so let's pin to top

Not quite, there should some Spark3.5 specific UTs(newly added in Spark3.5) we haven't ported yet.

**Comment by yma11** [comment] 2024-04-15 03:18
@zhouyuan This issue is used for tracking all failures in Spark3.5 UT and seems not all of them have been addressed yet. Should  we keep it open?

**Comment by gaoyangxiaozhu** [comment] 2024-04-16 03:42
@yma11 once the PR  https://github.com/apache/incubator-gluten/pull/5411 merged, you can mark below to be done:


SPARK-26708 Cache data and cached plan should stay consistent

SPARK-46590 adaptive query execution works correctly with broadcast join and union

SPARK-46590 adaptive query execution works correctly with cartesian join and union

SPARK-40618: Regression test for merging subquery bug with nested subqueries

SPARK-40615: Check unsupported data type when decorrelating subqueries

SPARK-40618: Regression test for merging subquery bug with nested subqueries

A cached table preserves the partitioning and ordering of its cached SparkPlan

SPARK-41896: Filter on row_index and a stored column at the same time

SPARK-43450: Filter on full _metadata column struct

SPARK-43450: Filter on aliased _metadata.row_index

**Comment by liujiayi771** [comment] 2024-04-17 14:29
@yma11 I will help to check the regr related UTs.

**Comment by gaoyangxiaozhu** [comment] 2024-04-19 10:21
for test case `SPARK-42782: Hive compatibility check for get_json_object`

it fail  due to this PR https://github.com/facebookincubator/velox/commit/20e467869b86d3c6d355cf52a550b94a10710479

the SIMD based `get_json_object` not cover case if path contains `*` example is `.store.book[*]`.
Need fix in velox part

**Comment by gaoyangxiaozhu** [comment] 2024-04-19 11:07
> @yma11 @zhouyuan I will help to check the regr related UTs.

oh, @yma11 i missed this comment, i have already send PR to fix it https://github.com/apache/incubator-gluten/pull/5466/files

**Closed** 2024-04-20 00:30 UTC
Labels: bug

**Comment by gaoyangxiaozhu** [comment] 2024-04-23 03:38
the task lists missed below 3 uts:

1. test udf
2. test udaf
3. GlutenDeleteFromTableSuite

@zhouyuan / @yma11 FYI, this PR is address to enable this remaning 3 UTs, after this PR is merged, all UT with `disabled for spark3.5` should be covered and enabled, except `Hive compatibility check for get_json_object` with is address by this PR https://github.com/apache/incubator-gluten/pull/5467
